/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JComponent;
import javax.swing.plaf.basic.BasicProgressBarUI;
import javax.swing.JProgressBar;

/**
 *
 * @author rnmel
 */
public class InicioSecion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSecion
     */
    public InicioSecion() {
        initComponents();
//        setIconImage(image);
        jProgress.setUI(new BasicProgressBarUI(){

            @Override
            protected void paintDeterminate(Graphics g, JComponent c) {
                super.paintDeterminate(g, c); //To change body of generated methods, choose Tools | Templates.
                Graphics2D G2= (Graphics2D)g;
            }
            
        });
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProgress = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jProgress1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(808, 452));

        jPanel1.setMaximumSize(new java.awt.Dimension(808, 452));
        jPanel1.setPreferredSize(new java.awt.Dimension(808, 452));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgress.setBackground(new java.awt.Color(66, 82, 116));
        jProgress.setForeground(new java.awt.Color(203, 151, 52));
        jProgress.setBorderPainted(false);
        jProgress.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel1.add(jProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 371, 700, 13));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Loading 3.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 840, -1));

        jProgress1.setBackground(new java.awt.Color(66, 82, 116));
        jProgress1.setForeground(new java.awt.Color(203, 151, 52));
        jProgress1.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel1.add(jProgress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 700, 11));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSecion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSecion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSecion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSecion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InicioSecion S = new InicioSecion();
                //new InicioSecion().setVisible(true);
            }
        });
        InicioSecion S = new InicioSecion();
        S.setVisible(true);
        try{
            for(int seg=0; seg<=100;seg++)
            {
                Thread.sleep(60);
                S.jProgress.setValue(seg);
            }
        }
        catch(Exception ex){         
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgress;
    private javax.swing.JProgressBar jProgress1;
    // End of variables declaration//GEN-END:variables
}
