package Vista;

import Controlador.ctrlMarca;
import Controlador.ctrlProducto;
import Modelo.productos;
import Modelo.CConexion;
import Modelo.MarcaProductos;
import javax.swing.ImageIcon;
import desplazable.Desface;
import java.awt.Color;
import java.awt.TextField;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Producto extends javax.swing.JFrame {

    
     
        productos ModeloProductos= new productos();
        Producto_Marca Pmarca= new Producto_Marca();
        
        
    
    Desface desplace;
    public Producto() {
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("/Vista/Iconos/CASA.png")).getImage());

        rsscalelabel.RSScaleLabel.setScaleLabel(txtLogo, "src/Vista/Iconos/logo.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(Casaicon, "src/Vista/Iconos/hogar.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(Productoicon, "src/Vista/Iconos/bolso.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(Clienteicon, "src/Vista/Iconos/usuario.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(Bitacoraicon, "src/Vista/Iconos/libreta.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(Trabajadoricon, "src/Vista/Iconos/obrero.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(Rutaicon, "src/Vista/Iconos/entrega.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(Bodegaicon, "src/Vista/Iconos/almacenamiento.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(txtBarras, "src/Vista/Iconos/lista.png");
        
        desplace = new Desface();
        
        TextPrompt nombre_pdt       = new TextPrompt("Nombre", txtNombre_pdt);        
        TextPrompt unidades_pdt     = new TextPrompt("Unidades", txtUnidades_pdt);
        TextPrompt PrecioCU         = new TextPrompt("Precio", txtPrecioUnitario_pdt);
        
        this.setLocationRelativeTo(null);        
        transpareciaBoton();
            
       
        ModeloProductos.RellenarMarcaCBX(jcbMarca_pdt);
        ModeloProductos.RellenarBodegaCBX(jcbBodega1);
        ModeloProductos.llenarBuscador(jcbBuscador);

    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MenuPlegable2 = new javax.swing.JPanel();
        btnCasa2 = new Vista.PanelCurvas();
        Casaicon2 = new javax.swing.JLabel();
        txtCasa2 = new javax.swing.JLabel();
        txtLogo2 = new javax.swing.JLabel();
        txtBarras2 = new javax.swing.JLabel();
        btnProducto2 = new Vista.PanelCurvas();
        Productoicon2 = new javax.swing.JLabel();
        txtproducto2 = new javax.swing.JLabel();
        btnTrabajador2 = new Vista.PanelCurvas();
        Trabajadoricon2 = new javax.swing.JLabel();
        txtEmpleado2 = new javax.swing.JLabel();
        btnBodega2 = new Vista.PanelCurvas();
        Bodegaicon2 = new javax.swing.JLabel();
        txtBodega2 = new javax.swing.JLabel();
        btnBitacora2 = new Vista.PanelCurvas();
        Bitacoraicon2 = new javax.swing.JLabel();
        txtBitacora2 = new javax.swing.JLabel();
        btnCliente2 = new Vista.PanelCurvas();
        Clienteicon2 = new javax.swing.JLabel();
        txtCliente2 = new javax.swing.JLabel();
        btnRuta2 = new Vista.PanelCurvas();
        Rutaicon2 = new javax.swing.JLabel();
        txtRuta2 = new javax.swing.JLabel();
        jpSubMenu = new javax.swing.JPanel();
        btnSubProductos = new Vista.PanelCurvas();
        txtSub = new javax.swing.JLabel();
        btnSubMarcas = new Vista.PanelCurvas();
        txtSub1 = new javax.swing.JLabel();
        jpProductos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProductos = new javax.swing.JTable();
        panelCurvas1 = new Vista.PanelCurvas();
        jLabel1 = new javax.swing.JLabel();
        panelCurvas2 = new Vista.PanelCurvas();
        txtNombre_pdt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelCurvas4 = new Vista.PanelCurvas();
        txtUnidades_pdt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        panelCurvas5 = new Vista.PanelCurvas();
        txtPrecioUnitario_pdt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcbMarca_pdt = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jcbBodega1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        agregar = new Vista.PanelCurvas();
        btnAgregar = new javax.swing.JButton();
        eliminar = new Vista.PanelCurvas();
        btnEliminar = new javax.swing.JButton();
        modificar = new Vista.PanelCurvas();
        btnModificar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jcbBuscador = new javax.swing.JComboBox<>();
        panelCurvas3 = new Vista.PanelCurvas();
        btnCXBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 760));
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 760));

        jPanel1.setBackground(new java.awt.Color(246, 234, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuPlegable2.setBackground(new java.awt.Color(64, 81, 115));
        MenuPlegable2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCasa2.setBackground(new java.awt.Color(64, 81, 115));
        btnCasa2.setRoundBottomLeft(25);
        btnCasa2.setRoundBottomRight(25);
        btnCasa2.setRoundTopLeft(25);
        btnCasa2.setRoundTopRight(25);
        btnCasa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCasa2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCasa2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCasa2MouseExited(evt);
            }
        });

        txtCasa2.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtCasa2.setForeground(new java.awt.Color(45, 40, 37));
        txtCasa2.setText("Inicio");

        javax.swing.GroupLayout btnCasa2Layout = new javax.swing.GroupLayout(btnCasa2);
        btnCasa2.setLayout(btnCasa2Layout);
        btnCasa2Layout.setHorizontalGroup(
            btnCasa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCasa2Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(txtCasa2)
                .addGap(18, 18, 18)
                .addComponent(Casaicon2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        btnCasa2Layout.setVerticalGroup(
            btnCasa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCasa2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(btnCasa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Casaicon2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCasa2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MenuPlegable2.add(btnCasa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 230, -1));
        MenuPlegable2.add(txtLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 90));

        txtBarras2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBarras2MouseClicked(evt);
            }
        });
        MenuPlegable2.add(txtBarras2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 53, 53));

        btnProducto2.setBackground(new java.awt.Color(64, 81, 115));
        btnProducto2.setRoundBottomLeft(25);
        btnProducto2.setRoundBottomRight(25);
        btnProducto2.setRoundTopLeft(25);
        btnProducto2.setRoundTopRight(25);
        btnProducto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProducto2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProducto2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProducto2MouseExited(evt);
            }
        });

        txtproducto2.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtproducto2.setForeground(new java.awt.Color(45, 40, 37));
        txtproducto2.setText("Productos");

        javax.swing.GroupLayout btnProducto2Layout = new javax.swing.GroupLayout(btnProducto2);
        btnProducto2.setLayout(btnProducto2Layout);
        btnProducto2Layout.setHorizontalGroup(
            btnProducto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnProducto2Layout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addComponent(txtproducto2)
                .addGap(18, 18, 18)
                .addComponent(Productoicon2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        btnProducto2Layout.setVerticalGroup(
            btnProducto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnProducto2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(btnProducto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtproducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Productoicon2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MenuPlegable2.add(btnProducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, 50));

        btnTrabajador2.setBackground(new java.awt.Color(64, 81, 115));
        btnTrabajador2.setRoundBottomLeft(25);
        btnTrabajador2.setRoundBottomRight(25);
        btnTrabajador2.setRoundTopLeft(25);
        btnTrabajador2.setRoundTopRight(25);
        btnTrabajador2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrabajador2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTrabajador2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTrabajador2MouseExited(evt);
            }
        });

        txtEmpleado2.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtEmpleado2.setForeground(new java.awt.Color(45, 40, 37));
        txtEmpleado2.setText("Empleados");

        javax.swing.GroupLayout btnTrabajador2Layout = new javax.swing.GroupLayout(btnTrabajador2);
        btnTrabajador2.setLayout(btnTrabajador2Layout);
        btnTrabajador2Layout.setHorizontalGroup(
            btnTrabajador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTrabajador2Layout.createSequentialGroup()
                .addGap(0, 58, Short.MAX_VALUE)
                .addComponent(txtEmpleado2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Trabajadoricon2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        btnTrabajador2Layout.setVerticalGroup(
            btnTrabajador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTrabajador2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(btnTrabajador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmpleado2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Trabajadoricon2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MenuPlegable2.add(btnTrabajador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 50));

        btnBodega2.setBackground(new java.awt.Color(64, 81, 115));
        btnBodega2.setRoundBottomLeft(25);
        btnBodega2.setRoundBottomRight(25);
        btnBodega2.setRoundTopLeft(25);
        btnBodega2.setRoundTopRight(25);
        btnBodega2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBodega2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBodega2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBodega2MouseExited(evt);
            }
        });

        txtBodega2.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtBodega2.setForeground(new java.awt.Color(45, 40, 37));
        txtBodega2.setText("Bodegas");

        javax.swing.GroupLayout btnBodega2Layout = new javax.swing.GroupLayout(btnBodega2);
        btnBodega2.setLayout(btnBodega2Layout);
        btnBodega2Layout.setHorizontalGroup(
            btnBodega2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBodega2Layout.createSequentialGroup()
                .addGap(0, 76, Short.MAX_VALUE)
                .addComponent(txtBodega2)
                .addGap(18, 18, 18)
                .addComponent(Bodegaicon2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        btnBodega2Layout.setVerticalGroup(
            btnBodega2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBodega2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(btnBodega2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBodega2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bodegaicon2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MenuPlegable2.add(btnBodega2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        btnBitacora2.setBackground(new java.awt.Color(64, 81, 115));
        btnBitacora2.setRoundBottomLeft(25);
        btnBitacora2.setRoundBottomRight(25);
        btnBitacora2.setRoundTopLeft(25);
        btnBitacora2.setRoundTopRight(25);
        btnBitacora2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBitacora2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBitacora2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBitacora2MouseExited(evt);
            }
        });

        txtBitacora2.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtBitacora2.setForeground(new java.awt.Color(45, 40, 37));
        txtBitacora2.setText("Bitacora");

        javax.swing.GroupLayout btnBitacora2Layout = new javax.swing.GroupLayout(btnBitacora2);
        btnBitacora2.setLayout(btnBitacora2Layout);
        btnBitacora2Layout.setHorizontalGroup(
            btnBitacora2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBitacora2Layout.createSequentialGroup()
                .addGap(0, 78, Short.MAX_VALUE)
                .addComponent(txtBitacora2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bitacoraicon2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        btnBitacora2Layout.setVerticalGroup(
            btnBitacora2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBitacora2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(btnBitacora2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBitacora2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bitacoraicon2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MenuPlegable2.add(btnBitacora2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, -1, -1));

        btnCliente2.setBackground(new java.awt.Color(64, 81, 115));
        btnCliente2.setRoundBottomLeft(25);
        btnCliente2.setRoundBottomRight(25);
        btnCliente2.setRoundTopLeft(25);
        btnCliente2.setRoundTopRight(25);
        btnCliente2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCliente2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCliente2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCliente2MouseExited(evt);
            }
        });

        txtCliente2.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtCliente2.setForeground(new java.awt.Color(45, 40, 37));
        txtCliente2.setText("Cliente");

        javax.swing.GroupLayout btnCliente2Layout = new javax.swing.GroupLayout(btnCliente2);
        btnCliente2.setLayout(btnCliente2Layout);
        btnCliente2Layout.setHorizontalGroup(
            btnCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCliente2Layout.createSequentialGroup()
                .addGap(0, 81, Short.MAX_VALUE)
                .addComponent(txtCliente2)
                .addGap(25, 25, 25)
                .addComponent(Clienteicon2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnCliente2Layout.setVerticalGroup(
            btnCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCliente2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(btnCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clienteicon2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MenuPlegable2.add(btnCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 230, -1));

        btnRuta2.setBackground(new java.awt.Color(64, 81, 115));
        btnRuta2.setRoundBottomLeft(25);
        btnRuta2.setRoundBottomRight(25);
        btnRuta2.setRoundTopLeft(25);
        btnRuta2.setRoundTopRight(25);
        btnRuta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRuta2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRuta2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRuta2MouseExited(evt);
            }
        });

        txtRuta2.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtRuta2.setForeground(new java.awt.Color(45, 40, 37));
        txtRuta2.setText("Rutas");

        javax.swing.GroupLayout btnRuta2Layout = new javax.swing.GroupLayout(btnRuta2);
        btnRuta2.setLayout(btnRuta2Layout);
        btnRuta2Layout.setHorizontalGroup(
            btnRuta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRuta2Layout.createSequentialGroup()
                .addGap(0, 101, Short.MAX_VALUE)
                .addComponent(txtRuta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Rutaicon2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        btnRuta2Layout.setVerticalGroup(
            btnRuta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRuta2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(btnRuta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRuta2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rutaicon2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MenuPlegable2.add(btnRuta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, -1));

        jPanel1.add(MenuPlegable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 0, 230, 760));

        jpSubMenu.setBackground(new java.awt.Color(64, 81, 115));
        jpSubMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubProductos.setBackground(new java.awt.Color(172, 147, 110));
        btnSubProductos.setRoundBottomLeft(25);
        btnSubProductos.setRoundBottomRight(25);
        btnSubProductos.setRoundTopLeft(25);
        btnSubProductos.setRoundTopRight(25);
        btnSubProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubProductosMouseExited(evt);
            }
        });

        txtSub.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtSub.setForeground(new java.awt.Color(51, 51, 51));
        txtSub.setText("Productos");

        javax.swing.GroupLayout btnSubProductosLayout = new javax.swing.GroupLayout(btnSubProductos);
        btnSubProductos.setLayout(btnSubProductosLayout);
        btnSubProductosLayout.setHorizontalGroup(
            btnSubProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSubProductosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtSub)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        btnSubProductosLayout.setVerticalGroup(
            btnSubProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSubProductosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtSub, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpSubMenu.add(btnSubProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 150, -1));

        btnSubMarcas.setBackground(new java.awt.Color(172, 147, 110));
        btnSubMarcas.setRoundBottomLeft(25);
        btnSubMarcas.setRoundBottomRight(25);
        btnSubMarcas.setRoundTopLeft(25);
        btnSubMarcas.setRoundTopRight(25);
        btnSubMarcas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubMarcasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubMarcasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubMarcasMouseExited(evt);
            }
        });

        txtSub1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtSub1.setForeground(new java.awt.Color(51, 51, 51));
        txtSub1.setText("Marca");

        javax.swing.GroupLayout btnSubMarcasLayout = new javax.swing.GroupLayout(btnSubMarcas);
        btnSubMarcas.setLayout(btnSubMarcasLayout);
        btnSubMarcasLayout.setHorizontalGroup(
            btnSubMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSubMarcasLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(txtSub1)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        btnSubMarcasLayout.setVerticalGroup(
            btnSubMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSubMarcasLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtSub1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpSubMenu.add(btnSubMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        jPanel1.add(jpSubMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 1040, 110));

        jpProductos.setBackground(new java.awt.Color(246, 234, 204));
        jpProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(172, 147, 110));

        tbProductos.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        tbProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbProductos.setFocusable(false);
        tbProductos.setRowHeight(30);
        tbProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProductos);

        jpProductos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 70, 560, 460));

        panelCurvas1.setBackground(new java.awt.Color(172, 147, 110));
        panelCurvas1.setRoundBottomLeft(35);
        panelCurvas1.setRoundBottomRight(35);
        panelCurvas1.setRoundTopLeft(35);
        panelCurvas1.setRoundTopRight(35);
        panelCurvas1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Nombre:");
        panelCurvas1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, 41));

        panelCurvas2.setBackground(new java.awt.Color(246, 234, 204));
        panelCurvas2.setRoundBottomLeft(25);
        panelCurvas2.setRoundBottomRight(25);
        panelCurvas2.setRoundTopLeft(25);
        panelCurvas2.setRoundTopRight(25);

        txtNombre_pdt.setBackground(new java.awt.Color(246, 234, 204));
        txtNombre_pdt.setBorder(null);
        txtNombre_pdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre_pdtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCurvas2Layout = new javax.swing.GroupLayout(panelCurvas2);
        panelCurvas2.setLayout(panelCurvas2Layout);
        panelCurvas2Layout.setHorizontalGroup(
            panelCurvas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurvas2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombre_pdt, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCurvas2Layout.setVerticalGroup(
            panelCurvas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurvas2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNombre_pdt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelCurvas1.add(panelCurvas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, 50));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Marca:");
        panelCurvas1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 140, 41));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Unidades:");
        panelCurvas1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 140, 41));

        panelCurvas4.setBackground(new java.awt.Color(246, 234, 204));
        panelCurvas4.setRoundBottomLeft(25);
        panelCurvas4.setRoundBottomRight(25);
        panelCurvas4.setRoundTopLeft(25);
        panelCurvas4.setRoundTopRight(25);

        txtUnidades_pdt.setBackground(new java.awt.Color(246, 234, 204));
        txtUnidades_pdt.setBorder(null);
        txtUnidades_pdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidades_pdtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCurvas4Layout = new javax.swing.GroupLayout(panelCurvas4);
        panelCurvas4.setLayout(panelCurvas4Layout);
        panelCurvas4Layout.setHorizontalGroup(
            panelCurvas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurvas4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUnidades_pdt, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCurvas4Layout.setVerticalGroup(
            panelCurvas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurvas4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtUnidades_pdt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelCurvas1.add(panelCurvas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 240, 50));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Precio C/U:");
        panelCurvas1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 140, 41));

        panelCurvas5.setBackground(new java.awt.Color(246, 234, 204));
        panelCurvas5.setRoundBottomLeft(25);
        panelCurvas5.setRoundBottomRight(25);
        panelCurvas5.setRoundTopLeft(25);
        panelCurvas5.setRoundTopRight(25);

        txtPrecioUnitario_pdt.setBackground(new java.awt.Color(246, 234, 204));
        txtPrecioUnitario_pdt.setBorder(null);
        txtPrecioUnitario_pdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioUnitario_pdtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCurvas5Layout = new javax.swing.GroupLayout(panelCurvas5);
        panelCurvas5.setLayout(panelCurvas5Layout);
        panelCurvas5Layout.setHorizontalGroup(
            panelCurvas5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurvas5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPrecioUnitario_pdt, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCurvas5Layout.setVerticalGroup(
            panelCurvas5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurvas5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPrecioUnitario_pdt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelCurvas1.add(panelCurvas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 240, 50));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Bodega:");
        panelCurvas1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 140, 41));

        jcbMarca_pdt.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        panelCurvas1.add(jcbMarca_pdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 240, 50));

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Informacion");
        panelCurvas1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 167, 41));

        jcbBodega1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        panelCurvas1.add(jcbBodega1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 240, 50));

        jpProductos.add(panelCurvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 410, 460));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Productos");
        jpProductos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 260, 41));

        agregar.setBackground(new java.awt.Color(172, 147, 110));
        agregar.setRoundBottomLeft(25);
        agregar.setRoundBottomRight(25);
        agregar.setRoundTopLeft(25);
        agregar.setRoundTopRight(25);

        btnAgregar.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout agregarLayout = new javax.swing.GroupLayout(agregar);
        agregar.setLayout(agregarLayout);
        agregarLayout.setHorizontalGroup(
            agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        agregarLayout.setVerticalGroup(
            agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpProductos.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, -1, 60));

        eliminar.setBackground(new java.awt.Color(172, 147, 110));
        eliminar.setRoundBottomLeft(25);
        eliminar.setRoundBottomRight(25);
        eliminar.setRoundTopLeft(25);
        eliminar.setRoundTopRight(25);

        btnEliminar.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eliminarLayout = new javax.swing.GroupLayout(eliminar);
        eliminar.setLayout(eliminarLayout);
        eliminarLayout.setHorizontalGroup(
            eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );
        eliminarLayout.setVerticalGroup(
            eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpProductos.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, -1, -1));

        modificar.setBackground(new java.awt.Color(172, 147, 110));
        modificar.setRoundBottomLeft(25);
        modificar.setRoundBottomRight(25);
        modificar.setRoundTopLeft(25);
        modificar.setRoundTopRight(25);

        btnModificar.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");

        javax.swing.GroupLayout modificarLayout = new javax.swing.GroupLayout(modificar);
        modificar.setLayout(modificarLayout);
        modificarLayout.setHorizontalGroup(
            modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        modificarLayout.setVerticalGroup(
            modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpProductos.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 550, 160, 60));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Buscar:");
        jpProductos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 100, 41));

        jcbBuscador.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jpProductos.add(jcbBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 240, 40));

        btnCXBuscar.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        btnCXBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnCXBuscar.setText("Buscar");
        btnCXBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCXBuscarMouseClicked(evt);
            }
        });
        btnCXBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCXBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCurvas3Layout = new javax.swing.GroupLayout(panelCurvas3);
        panelCurvas3.setLayout(panelCurvas3Layout);
        panelCurvas3Layout.setHorizontalGroup(
            panelCurvas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurvas3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCXBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelCurvas3Layout.setVerticalGroup(
            panelCurvas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurvas3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCXBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpProductos.add(panelCurvas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 120, 40));

        jPanel1.add(jpProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 1000, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void txtNombre_pdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre_pdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre_pdtActionPerformed

    private void txtUnidades_pdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidades_pdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidades_pdtActionPerformed

    private void txtPrecioUnitario_pdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioUnitario_pdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioUnitario_pdtActionPerformed

    private void btnSubProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubProductosMouseClicked
//        ModeloProductos.RellenarMarcaCBX(jcbBuscador);
//        ModeloProductos.RellenarBodegaCBX(jcbBuscador);
    }//GEN-LAST:event_btnSubProductosMouseClicked

    private void btnSubProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubProductosMouseEntered
        btnSubProductos.setBackground(new Color(45,40,37));
        txtSub.setForeground(Color.white);
        
        
    }//GEN-LAST:event_btnSubProductosMouseEntered

    private void btnSubProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubProductosMouseExited
        btnSubProductos.setBackground(new Color(172,147,110));
        txtSub.setForeground(Color.black);
    }//GEN-LAST:event_btnSubProductosMouseExited

    private void btnSubMarcasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubMarcasMouseClicked
        this.dispose();
        Pmarca.NIT();
    }//GEN-LAST:event_btnSubMarcasMouseClicked

    private void btnSubMarcasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubMarcasMouseEntered
        btnSubMarcas.setBackground(new Color(45,40,37));
        txtSub1.setForeground(Color.white);
    }//GEN-LAST:event_btnSubMarcasMouseEntered

    private void btnSubMarcasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubMarcasMouseExited
        btnSubMarcas.setBackground(new Color(64,81,152));
    }//GEN-LAST:event_btnSubMarcasMouseExited

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
//        String SQL = "insert into tbProductos (Prod_Nombre, Prod_idMarca, Prod_Unidades, Prod_PrecioUnitario, idBodega) values(?,?,?,?,?)";
//        try {
//            PreparedStatement AProducto = CConexion.getConexion().prepareStatement(SQL);
//            AProducto.setString (1, txtNombre_pdt.getText());
//            AProducto.setString(2,  jcbMarca_pdt.getSelectedItem().toString());
//            AProducto.setInt    (3, Integer.parseInt(txtUnidades_pdt.getText()) );
//            AProducto.setString (4, txtPrecioUnitario_pdt.getText());
//            AProducto.setString(5, jcbMarca_pdt.getSelectedItem().toString());
//            AProducto.executeUpdate();
//            JOptionPane.showMessageDialog(null, "El producto  se agrego correctamente");
//            MostrarProductos();
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Error "+ e.toString());                       
//        }
        
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void tbProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProductosMouseClicked
        int filaSeleccionada = tbProductos.getSelectedRow();

        String nombre = tbProductos.getValueAt(filaSeleccionada, 1).toString();
        String marca = tbProductos.getValueAt(filaSeleccionada, 2).toString();
        String unidades = tbProductos.getValueAt(filaSeleccionada, 3).toString();
        String Precio   = tbProductos.getValueAt(filaSeleccionada, 4).toString();
        String bodega = tbProductos.getValueAt(filaSeleccionada, 5).toString();

        txtNombre_pdt.setText(nombre);
        txtUnidades_pdt.setText(unidades);
        txtPrecioUnitario_pdt.setText(Precio);
    }//GEN-LAST:event_tbProductosMouseClicked

    private void btnCXBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCXBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCXBuscarActionPerformed

    private void btnCXBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCXBuscarMouseClicked
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new Object[]{"ID", "Nombre","Marca","Unidades","Precio C/U", "Bodega"});
        try {
            Statement st= CConexion.getConexion().createStatement();
//                String SQL ="select tbProductos.idProducto, tbProductos.Prod_Nombre, tbMarcaProductos.MP_Nombre, tbProductos.Prod_Unidades, tbProductos.Prod_PrecioUnitario, tbBodegas.bdg_nombre"+
//                    " from tbProductos inner join tbMarcaProductos  on tbProductos.id_MP = tbMarcaProductos.id_MP inner join tbBodegas on tbProductos.idBodega = tbBodegas.idBodega";
            
            String SQL="select tbProductos.idProducto, tbProductos.Prod_Nombre, tbMarcaProductos.MP_Nombre, tbProductos.Prod_Unidades, tbProductos.Prod_PrecioUnitario, tbBodegas.bdg_nombre\n" +
            "from tbProductos inner join tbMarcaProductos  on tbProductos.id_MP = tbMarcaProductos.id_MP inner join tbBodegas on tbProductos.idBodega = tbBodegas.idBodega where MP_Nombre='"+jcbBuscador.getSelectedItem()+"'";
            
            
            
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()) {
                modelo.addRow(new Object[]{rs.getInt("idProducto"), rs.getString("Prod_Nombre"), rs.getString("MP_Nombre"), rs.getInt("Prod_Unidades"), rs.getFloat("Prod_PrecioUnitario"), rs.getString("bdg_nombre")});
            }
            tbProductos.setModel(modelo);            
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, "Error 3"+e.getMessage());                
        }
    }//GEN-LAST:event_btnCXBuscarMouseClicked

    private void btnCasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCasaMouseClicked

    }//GEN-LAST:event_btnCasaMouseClicked

    private void btnCasaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCasaMouseEntered
        btnCasa.setBackground(new Color(45,40,37));
        txtCasa.setForeground(Color.white);
    }//GEN-LAST:event_btnCasaMouseEntered

    private void btnCasaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCasaMouseExited
        btnCasa.setBackground(new Color(64,81,115));
        txtCasa.setForeground(new Color(45,40,37));
    }//GEN-LAST:event_btnCasaMouseExited

    private void txtBarrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBarrasMouseClicked
        if (MenuPlegable.getX()==-150) {
            desplace.desplazarDerecha(MenuPlegable, MenuPlegable.getX(), 0, 15, 10);
        } else if(MenuPlegable.getX() == 0) {
            desplace.desplazarIzquierda(MenuPlegable, MenuPlegable.getX(), -150, 15, 10);
        }
    }//GEN-LAST:event_txtBarrasMouseClicked

    private void btnProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoMouseClicked
        Producto producto = new Producto();
        producto.NIT();
        //  producto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProductoMouseClicked

    private void btnProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoMouseEntered
        btnProducto.setBackground(new Color(45,40,37));
        txtproducto.setForeground(Color.white);
    }//GEN-LAST:event_btnProductoMouseEntered

    private void btnProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoMouseExited
        btnProducto.setBackground(new Color(64,81,115));
        txtproducto.setForeground(new Color(45,40,37));
    }//GEN-LAST:event_btnProductoMouseExited

    private void btnTrabajadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrabajadorMouseClicked
        VEmpleados empleados = new VEmpleados();
        empleados.INIT();
        this.dispose();
    }//GEN-LAST:event_btnTrabajadorMouseClicked

    private void btnTrabajadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrabajadorMouseEntered
        btnTrabajador.setBackground(new Color(45,40,37));
        txtEmpleado.setForeground(Color.white);
    }//GEN-LAST:event_btnTrabajadorMouseEntered

    private void btnTrabajadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrabajadorMouseExited
        btnTrabajador.setBackground(new Color(64,81,115));
        txtEmpleado.setForeground(new Color(45,40,37));
    }//GEN-LAST:event_btnTrabajadorMouseExited

    private void btnBodegaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBodegaMouseClicked
        Bodega bodegas = new Bodega();
        bodegas.INIT();
        this.dispose();
    }//GEN-LAST:event_btnBodegaMouseClicked

    private void btnBodegaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBodegaMouseEntered
        btnBodega.setBackground(new Color(45,40,37));
        txtBodega.setForeground(Color.white);
    }//GEN-LAST:event_btnBodegaMouseEntered

    private void btnBodegaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBodegaMouseExited
        btnBodega.setBackground(new Color(64,81,115));
        txtBodega.setForeground(new Color(45,40,37));
    }//GEN-LAST:event_btnBodegaMouseExited

    private void btnBitacoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBitacoraMouseClicked
        Bitacora bitacora = new Bitacora();
        bitacora.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBitacoraMouseClicked

    private void btnBitacoraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBitacoraMouseEntered
        btnBitacora.setBackground(new Color(45,40,37));
        txtBitacora.setForeground(Color.white);
    }//GEN-LAST:event_btnBitacoraMouseEntered

    private void btnBitacoraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBitacoraMouseExited
        btnBitacora.setBackground(new Color(64,81,115));
        txtBitacora.setForeground(new Color(45,40,37));
    }//GEN-LAST:event_btnBitacoraMouseExited

    private void btnClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMouseClicked
        VCliente vista= new VCliente();
        vista.INIT();
        this.dispose();
    }//GEN-LAST:event_btnClienteMouseClicked

    private void btnClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMouseEntered
        btnCliente.setBackground(new Color(45,40,37));
        txtCliente.setForeground(Color.white);
    }//GEN-LAST:event_btnClienteMouseEntered

    private void btnClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMouseExited
        btnCliente.setBackground(new Color(64,81,115));
        txtCliente.setForeground(new Color(45,40,37));
    }//GEN-LAST:event_btnClienteMouseExited

    private void btnRutaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRutaMouseClicked
        VDatosDis rutas = new VDatosDis();
        rutas.INIT();
        this.dispose();
    }//GEN-LAST:event_btnRutaMouseClicked

    private void btnRutaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRutaMouseEntered
        btnRuta.setBackground(new Color(45,40,37));
        txtRuta.setForeground(Color.white);
    }//GEN-LAST:event_btnRutaMouseEntered

    private void btnRutaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRutaMouseExited
        btnRuta.setBackground(new Color(64,81,115));
        txtRuta.setForeground(new Color(45,40,37));
    }//GEN-LAST:event_btnRutaMouseExited

    private void btnCasa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCasa2MouseClicked

    }//GEN-LAST:event_btnCasa2MouseClicked

    private void btnCasa2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCasa2MouseEntered
        btnCasa.setBackground(new Color(45,40,37));
        txtCasa.setForeground(Color.white);
    }//GEN-LAST:event_btnCasa2MouseEntered

    private void btnCasa2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCasa2MouseExited
        btnCasa.setBackground(new Color(64,81,115));
        txtCasa.setForeground(new Color(45,40,37));
    }//GEN-LAST:event_btnCasa2MouseExited

    private void txtBarras2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBarras2MouseClicked
        if (MenuPlegable.getX()==-150) {
            desplace.desplazarDerecha(MenuPlegable, MenuPlegable.getX(), 0, 15, 10);
        } else if(MenuPlegable.getX() == 0) {
            desplace.desplazarIzquierda(MenuPlegable, MenuPlegable.getX(), -150, 15, 10);
        }
    }//GEN-LAST:event_txtBarras2MouseClicked

    private void btnProducto2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProducto2MouseClicked
        Producto producto = new Producto();
        producto.NIT();
        //  producto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProducto2MouseClicked

    private void btnProducto2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProducto2MouseEntered
        btnProducto.setBackground(new Color(45,40,37));
        txtproducto.setForeground(Color.white);
    }//GEN-LAST:event_btnProducto2MouseEntered

    private void btnProducto2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProducto2MouseExited
        btnProducto.setBackground(new Color(64,81,115));
        txtproducto.setForeground(new Color(45,40,37));
    }//GEN-LAST:event_btnProducto2MouseExited

    private void btnTrabajador2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrabajador2MouseClicked
        VEmpleados empleados = new VEmpleados();
        empleados.INIT();
        this.dispose();
    }//GEN-LAST:event_btnTrabajador2MouseClicked

    private void btnTrabajador2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrabajador2MouseEntered
        btnTrabajador.setBackground(new Color(45,40,37));
        txtEmpleado.setForeground(Color.white);
    }//GEN-LAST:event_btnTrabajador2MouseEntered

    private void btnTrabajador2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrabajador2MouseExited
        btnTrabajador.setBackground(new Color(64,81,115));
        txtEmpleado.setForeground(new Color(45,40,37));
    }//GEN-LAST:event_btnTrabajador2MouseExited

    private void btnBodega2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBodega2MouseClicked
        Bodega bodegas = new Bodega();
        bodegas.INIT();
        this.dispose();
    }//GEN-LAST:event_btnBodega2MouseClicked

    private void btnBodega2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBodega2MouseEntered
        btnBodega.setBackground(new Color(45,40,37));
        txtBodega.setForeground(Color.white);
    }//GEN-LAST:event_btnBodega2MouseEntered

    private void btnBodega2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBodega2MouseExited
        btnBodega.setBackground(new Color(64,81,115));
        txtBodega.setForeground(new Color(45,40,37));
    }//GEN-LAST:event_btnBodega2MouseExited

    private void btnBitacora2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBitacora2MouseClicked
        Bitacora bitacora = new Bitacora();
        bitacora.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBitacora2MouseClicked

    private void btnBitacora2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBitacora2MouseEntered
        btnBitacora.setBackground(new Color(45,40,37));
        txtBitacora.setForeground(Color.white);
    }//GEN-LAST:event_btnBitacora2MouseEntered

    private void btnBitacora2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBitacora2MouseExited
        btnBitacora.setBackground(new Color(64,81,115));
        txtBitacora.setForeground(new Color(45,40,37));
    }//GEN-LAST:event_btnBitacora2MouseExited

    private void btnCliente2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCliente2MouseClicked
        VCliente vista= new VCliente();
        vista.INIT();
        this.dispose();
    }//GEN-LAST:event_btnCliente2MouseClicked

    private void btnCliente2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCliente2MouseEntered
        btnCliente.setBackground(new Color(45,40,37));
        txtCliente.setForeground(Color.white);
    }//GEN-LAST:event_btnCliente2MouseEntered

    private void btnCliente2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCliente2MouseExited
        btnCliente.setBackground(new Color(64,81,115));
        txtCliente.setForeground(new Color(45,40,37));
    }//GEN-LAST:event_btnCliente2MouseExited

    private void btnRuta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRuta2MouseClicked
        VDatosDis rutas = new VDatosDis();
        rutas.INIT();
        this.dispose();
    }//GEN-LAST:event_btnRuta2MouseClicked

    private void btnRuta2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRuta2MouseEntered
        btnRuta.setBackground(new Color(45,40,37));
        txtRuta.setForeground(Color.white);
    }//GEN-LAST:event_btnRuta2MouseEntered

    private void btnRuta2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRuta2MouseExited
        btnRuta.setBackground(new Color(64,81,115));
        txtRuta.setForeground(new Color(45,40,37));
    }//GEN-LAST:event_btnRuta2MouseExited

    /**
     * @param args the command line arguments
     */
    
            
    public void NIT(){
        productos modeloProductos= new productos();
        Producto vista= new Producto();
        ctrlProducto control = new ctrlProducto(modeloProductos,vista);
        modeloProductos.MostrarProductos(vista);
        
        vista.setVisible(true);
        
    }
    
    public void transpareciaBoton(){
        btnAgregar.setOpaque(false);        
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setBorderPainted(false);
        btnEliminar.setOpaque(false);        
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setBorderPainted(false);
        btnModificar.setOpaque(false);        
        btnModificar.setContentAreaFilled(false);
        btnModificar.setBorderPainted(false);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bitacoraicon;
    private javax.swing.JLabel Bitacoraicon2;
    private javax.swing.JLabel Bodegaicon;
    private javax.swing.JLabel Bodegaicon2;
    private javax.swing.JLabel Casaicon;
    private javax.swing.JLabel Casaicon2;
    private javax.swing.JLabel Clienteicon;
    private javax.swing.JLabel Clienteicon2;
    private javax.swing.JPanel MenuPlegable;
    private javax.swing.JPanel MenuPlegable2;
    private javax.swing.JLabel Productoicon;
    private javax.swing.JLabel Productoicon2;
    private javax.swing.JLabel Rutaicon;
    private javax.swing.JLabel Rutaicon2;
    private javax.swing.JLabel Trabajadoricon;
    private javax.swing.JLabel Trabajadoricon2;
    private Vista.PanelCurvas agregar;
    public javax.swing.JButton btnAgregar;
    private Vista.PanelCurvas btnBitacora;
    private Vista.PanelCurvas btnBitacora2;
    private Vista.PanelCurvas btnBodega;
    private Vista.PanelCurvas btnBodega2;
    public javax.swing.JButton btnCXBuscar;
    private Vista.PanelCurvas btnCasa;
    private Vista.PanelCurvas btnCasa2;
    private Vista.PanelCurvas btnCliente;
    private Vista.PanelCurvas btnCliente2;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnModificar;
    private Vista.PanelCurvas btnProducto;
    private Vista.PanelCurvas btnProducto2;
    private Vista.PanelCurvas btnRuta;
    private Vista.PanelCurvas btnRuta2;
    private Vista.PanelCurvas btnSubMarcas;
    private Vista.PanelCurvas btnSubProductos;
    private Vista.PanelCurvas btnTrabajador;
    private Vista.PanelCurvas btnTrabajador2;
    private Vista.PanelCurvas eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox<String> jcbBodega1;
    public javax.swing.JComboBox<String> jcbBuscador;
    public javax.swing.JComboBox<String> jcbMarca_pdt;
    public javax.swing.JPanel jpProductos;
    private javax.swing.JPanel jpSubMenu;
    private Vista.PanelCurvas modificar;
    private Vista.PanelCurvas panelCurvas1;
    private Vista.PanelCurvas panelCurvas2;
    private Vista.PanelCurvas panelCurvas3;
    private Vista.PanelCurvas panelCurvas4;
    private Vista.PanelCurvas panelCurvas5;
    public javax.swing.JTable tbProductos;
    private javax.swing.JLabel txtBarras;
    private javax.swing.JLabel txtBarras2;
    private javax.swing.JLabel txtBitacora;
    private javax.swing.JLabel txtBitacora2;
    private javax.swing.JLabel txtBodega;
    private javax.swing.JLabel txtBodega2;
    private javax.swing.JLabel txtCasa;
    private javax.swing.JLabel txtCasa2;
    private javax.swing.JLabel txtCliente;
    private javax.swing.JLabel txtCliente2;
    private javax.swing.JLabel txtEmpleado;
    private javax.swing.JLabel txtEmpleado2;
    private javax.swing.JLabel txtLogo;
    private javax.swing.JLabel txtLogo2;
    public javax.swing.JTextField txtNombre_pdt;
    public javax.swing.JTextField txtPrecioUnitario_pdt;
    private javax.swing.JLabel txtRuta;
    private javax.swing.JLabel txtRuta2;
    private javax.swing.JLabel txtSub;
    private javax.swing.JLabel txtSub1;
    public javax.swing.JTextField txtUnidades_pdt;
    private javax.swing.JLabel txtproducto;
    private javax.swing.JLabel txtproducto2;
    // End of variables declaration//GEN-END:variables
}
