/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Repartidor;

import Modelo.BitacoraDistribuciones;
import Vista.Controlador.*;
import Vista.*;
import javax.swing.ImageIcon;
import desplazable.Desface;
import java.awt.Color;

/**
 *
 * @author rnmel
 */
public class RMain extends javax.swing.JFrame {

    Desface desplace;
    public RMain() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Vista/Iconos/CASA.png")).getImage());

          rsscalelabel.RSScaleLabel.setScaleLabel(txtLogo, "src/Vista/Iconos/logo.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(Casaicon, "src/Vista/Iconos/hogar.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(Productoicon, "src/Vista/Iconos/bolso.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(Clienteicon, "src/Vista/Iconos/usuario.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(Rutaicon, "src/Vista/Iconos/entrega.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(txtBarras, "src/Vista/Iconos/lista.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(icoCarro, "src/Vista/Iconos/vehiculo.png");
        
        desplace = new Desface();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MenuPlegable = new javax.swing.JPanel();
        btnCasa = new Vista.PanelCurvas();
        Casaicon = new javax.swing.JLabel();
        txtCasa = new javax.swing.JLabel();
        txtLogo = new javax.swing.JLabel();
        txtBarras = new javax.swing.JLabel();
        btnProducto = new Vista.PanelCurvas();
        Productoicon = new javax.swing.JLabel();
        txtproducto = new javax.swing.JLabel();
        btnCliente = new Vista.PanelCurvas();
        Clienteicon = new javax.swing.JLabel();
        txtCliente = new javax.swing.JLabel();
        btnRuta = new Vista.PanelCurvas();
        Rutaicon = new javax.swing.JLabel();
        txtRuta = new javax.swing.JLabel();
        btnVehiculos = new Vista.PanelCurvas();
        icoCarro = new javax.swing.JLabel();
        txtCliente2 = new javax.swing.JLabel();
        btnSalir = new Vista.PanelCurvas();
        logOut = new javax.swing.JLabel();
        txtBitacora2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        MenuPlegable1 = new javax.swing.JPanel();
        btnCasa1 = new Vista.PanelCurvas();
        Casaicon1 = new javax.swing.JLabel();
        txtCasa1 = new javax.swing.JLabel();
        txtLogo1 = new javax.swing.JLabel();
        txtBarras1 = new javax.swing.JLabel();
        btnProducto1 = new Vista.PanelCurvas();
        Productoicon1 = new javax.swing.JLabel();
        txtproducto1 = new javax.swing.JLabel();
        btnCliente1 = new Vista.PanelCurvas();
        Clienteicon1 = new javax.swing.JLabel();
        txtCliente1 = new javax.swing.JLabel();
        btnRuta1 = new Vista.PanelCurvas();
        Rutaicon1 = new javax.swing.JLabel();
        txtRuta1 = new javax.swing.JLabel();
        btnVehiculos1 = new Vista.PanelCurvas();
        icoCarro1 = new javax.swing.JLabel();
        txtCliente3 = new javax.swing.JLabel();
        btnSalir1 = new Vista.PanelCurvas();
        logOut1 = new javax.swing.JLabel();
        txtBitacora3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEnvios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 760));
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 760));

        jPanel1.setBackground(new java.awt.Color(246, 234, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuPlegable.setBackground(new java.awt.Color(64, 81, 115));
        MenuPlegable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCasa.setBackground(new java.awt.Color(64, 81, 115));
        btnCasa.setRoundBottomLeft(25);
        btnCasa.setRoundBottomRight(25);
        btnCasa.setRoundTopLeft(25);
        btnCasa.setRoundTopRight(25);
        btnCasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCasaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCasaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCasaMouseExited(evt);
            }
        });

        txtCasa.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtCasa.setForeground(new java.awt.Color(255, 255, 255));
        txtCasa.setText("Inicio");

        javax.swing.GroupLayout btnCasaLayout = new javax.swing.GroupLayout(btnCasa);
        btnCasa.setLayout(btnCasaLayout);
        btnCasaLayout.setHorizontalGroup(
            btnCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCasaLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(txtCasa)
                .addGap(18, 18, 18)
                .addComponent(Casaicon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        btnCasaLayout.setVerticalGroup(
            btnCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCasaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(btnCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Casaicon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MenuPlegable.add(btnCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 230, -1));
        MenuPlegable.add(txtLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 90));

        txtBarras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBarrasMouseClicked(evt);
            }
        });
        MenuPlegable.add(txtBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 53, 53));

        btnProducto.setBackground(new java.awt.Color(64, 81, 115));
        btnProducto.setRoundBottomLeft(25);
        btnProducto.setRoundBottomRight(25);
        btnProducto.setRoundTopLeft(25);
        btnProducto.setRoundTopRight(25);
        btnProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProductoMouseExited(evt);
            }
        });

        txtproducto.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtproducto.setForeground(new java.awt.Color(255, 255, 255));
        txtproducto.setText("Productos");

        javax.swing.GroupLayout btnProductoLayout = new javax.swing.GroupLayout(btnProducto);
        btnProducto.setLayout(btnProductoLayout);
        btnProductoLayout.setHorizontalGroup(
            btnProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnProductoLayout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addComponent(txtproducto)
                .addGap(18, 18, 18)
                .addComponent(Productoicon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        btnProductoLayout.setVerticalGroup(
            btnProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnProductoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(btnProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Productoicon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MenuPlegable.add(btnProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 50));

        btnCliente.setBackground(new java.awt.Color(64, 81, 115));
        btnCliente.setRoundBottomLeft(25);
        btnCliente.setRoundBottomRight(25);
        btnCliente.setRoundTopLeft(25);
        btnCliente.setRoundTopRight(25);
        btnCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClienteMouseExited(evt);
            }
        });

        txtCliente.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtCliente.setText("Cliente");

        javax.swing.GroupLayout btnClienteLayout = new javax.swing.GroupLayout(btnCliente);
        btnCliente.setLayout(btnClienteLayout);
        btnClienteLayout.setHorizontalGroup(
            btnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnClienteLayout.createSequentialGroup()
                .addGap(0, 86, Short.MAX_VALUE)
                .addComponent(txtCliente)
                .addGap(25, 25, 25)
                .addComponent(Clienteicon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnClienteLayout.setVerticalGroup(
            btnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnClienteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(btnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clienteicon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MenuPlegable.add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 230, -1));

        btnRuta.setBackground(new java.awt.Color(64, 81, 115));
        btnRuta.setRoundBottomLeft(25);
        btnRuta.setRoundBottomRight(25);
        btnRuta.setRoundTopLeft(25);
        btnRuta.setRoundTopRight(25);
        btnRuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRutaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRutaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRutaMouseExited(evt);
            }
        });

        txtRuta.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtRuta.setForeground(new java.awt.Color(255, 255, 255));
        txtRuta.setText("Rutas");

        javax.swing.GroupLayout btnRutaLayout = new javax.swing.GroupLayout(btnRuta);
        btnRuta.setLayout(btnRutaLayout);
        btnRutaLayout.setHorizontalGroup(
            btnRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRutaLayout.createSequentialGroup()
                .addGap(0, 101, Short.MAX_VALUE)
                .addComponent(txtRuta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Rutaicon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        btnRutaLayout.setVerticalGroup(
            btnRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRutaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(btnRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rutaicon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MenuPlegable.add(btnRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, -1, -1));

        btnVehiculos.setBackground(new java.awt.Color(64, 81, 115));
        btnVehiculos.setRoundBottomLeft(25);
        btnVehiculos.setRoundBottomRight(25);
        btnVehiculos.setRoundTopLeft(25);
        btnVehiculos.setRoundTopRight(25);
        btnVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVehiculosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVehiculosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVehiculosMouseExited(evt);
            }
        });

        icoCarro.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        icoCarro.setForeground(new java.awt.Color(255, 255, 255));

        txtCliente2.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtCliente2.setForeground(new java.awt.Color(255, 255, 255));
        txtCliente2.setText("Vehiculos");

        javax.swing.GroupLayout btnVehiculosLayout = new javax.swing.GroupLayout(btnVehiculos);
        btnVehiculos.setLayout(btnVehiculosLayout);
        btnVehiculosLayout.setHorizontalGroup(
            btnVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVehiculosLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(txtCliente2)
                .addGap(18, 18, 18)
                .addComponent(icoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnVehiculosLayout.setVerticalGroup(
            btnVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icoCarro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVehiculosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCliente2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        MenuPlegable.add(btnVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 230, 53));

        btnSalir.setBackground(new java.awt.Color(64, 81, 115));
        btnSalir.setRoundBottomLeft(25);
        btnSalir.setRoundBottomRight(25);
        btnSalir.setRoundTopLeft(25);
        btnSalir.setRoundTopRight(25);
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });

        txtBitacora2.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtBitacora2.setForeground(new java.awt.Color(255, 153, 153));
        txtBitacora2.setText("Cerrar secion");

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSalirLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(txtBitacora2)
                .addGap(18, 18, 18)
                .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btnSalirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBitacora2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        MenuPlegable.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, -1, -1));

        jPanel1.add(MenuPlegable, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 0, 230, 810));

        jPanel2.setBackground(new java.awt.Color(246, 234, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuPlegable1.setBackground(new java.awt.Color(64, 81, 115));
        MenuPlegable1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCasa1.setBackground(new java.awt.Color(64, 81, 115));
        btnCasa1.setRoundBottomLeft(25);
        btnCasa1.setRoundBottomRight(25);
        btnCasa1.setRoundTopLeft(25);
        btnCasa1.setRoundTopRight(25);
        btnCasa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCasa1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCasa1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCasa1MouseExited(evt);
            }
        });

        txtCasa1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtCasa1.setForeground(new java.awt.Color(255, 255, 255));
        txtCasa1.setText("Inicio");

        javax.swing.GroupLayout btnCasa1Layout = new javax.swing.GroupLayout(btnCasa1);
        btnCasa1.setLayout(btnCasa1Layout);
        btnCasa1Layout.setHorizontalGroup(
            btnCasa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCasa1Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(txtCasa1)
                .addGap(18, 18, 18)
                .addComponent(Casaicon1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        btnCasa1Layout.setVerticalGroup(
            btnCasa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCasa1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(btnCasa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Casaicon1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCasa1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MenuPlegable1.add(btnCasa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 230, -1));
        MenuPlegable1.add(txtLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 90));

        txtBarras1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBarras1MouseClicked(evt);
            }
        });
        MenuPlegable1.add(txtBarras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 53, 53));

        btnProducto1.setBackground(new java.awt.Color(64, 81, 115));
        btnProducto1.setRoundBottomLeft(25);
        btnProducto1.setRoundBottomRight(25);
        btnProducto1.setRoundTopLeft(25);
        btnProducto1.setRoundTopRight(25);
        btnProducto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProducto1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProducto1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProducto1MouseExited(evt);
            }
        });

        txtproducto1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtproducto1.setForeground(new java.awt.Color(255, 255, 255));
        txtproducto1.setText("Productos");

        javax.swing.GroupLayout btnProducto1Layout = new javax.swing.GroupLayout(btnProducto1);
        btnProducto1.setLayout(btnProducto1Layout);
        btnProducto1Layout.setHorizontalGroup(
            btnProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnProducto1Layout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addComponent(txtproducto1)
                .addGap(18, 18, 18)
                .addComponent(Productoicon1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        btnProducto1Layout.setVerticalGroup(
            btnProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnProducto1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(btnProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtproducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Productoicon1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MenuPlegable1.add(btnProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 50));

        btnCliente1.setBackground(new java.awt.Color(64, 81, 115));
        btnCliente1.setRoundBottomLeft(25);
        btnCliente1.setRoundBottomRight(25);
        btnCliente1.setRoundTopLeft(25);
        btnCliente1.setRoundTopRight(25);
        btnCliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCliente1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCliente1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCliente1MouseExited(evt);
            }
        });

        txtCliente1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtCliente1.setForeground(new java.awt.Color(255, 255, 255));
        txtCliente1.setText("Cliente");

        javax.swing.GroupLayout btnCliente1Layout = new javax.swing.GroupLayout(btnCliente1);
        btnCliente1.setLayout(btnCliente1Layout);
        btnCliente1Layout.setHorizontalGroup(
            btnCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCliente1Layout.createSequentialGroup()
                .addGap(0, 86, Short.MAX_VALUE)
                .addComponent(txtCliente1)
                .addGap(25, 25, 25)
                .addComponent(Clienteicon1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnCliente1Layout.setVerticalGroup(
            btnCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCliente1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(btnCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clienteicon1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MenuPlegable1.add(btnCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 230, -1));

        btnRuta1.setBackground(new java.awt.Color(64, 81, 115));
        btnRuta1.setRoundBottomLeft(25);
        btnRuta1.setRoundBottomRight(25);
        btnRuta1.setRoundTopLeft(25);
        btnRuta1.setRoundTopRight(25);
        btnRuta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRuta1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRuta1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRuta1MouseExited(evt);
            }
        });

        txtRuta1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtRuta1.setForeground(new java.awt.Color(255, 255, 255));
        txtRuta1.setText("Rutas");

        javax.swing.GroupLayout btnRuta1Layout = new javax.swing.GroupLayout(btnRuta1);
        btnRuta1.setLayout(btnRuta1Layout);
        btnRuta1Layout.setHorizontalGroup(
            btnRuta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRuta1Layout.createSequentialGroup()
                .addGap(0, 101, Short.MAX_VALUE)
                .addComponent(txtRuta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Rutaicon1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        btnRuta1Layout.setVerticalGroup(
            btnRuta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRuta1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(btnRuta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRuta1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rutaicon1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MenuPlegable1.add(btnRuta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, -1, -1));

        btnVehiculos1.setBackground(new java.awt.Color(64, 81, 115));
        btnVehiculos1.setRoundBottomLeft(25);
        btnVehiculos1.setRoundBottomRight(25);
        btnVehiculos1.setRoundTopLeft(25);
        btnVehiculos1.setRoundTopRight(25);
        btnVehiculos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVehiculos1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVehiculos1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVehiculos1MouseExited(evt);
            }
        });

        icoCarro1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        icoCarro1.setForeground(new java.awt.Color(255, 255, 255));

        txtCliente3.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtCliente3.setForeground(new java.awt.Color(255, 255, 255));
        txtCliente3.setText("Vehiculos");

        javax.swing.GroupLayout btnVehiculos1Layout = new javax.swing.GroupLayout(btnVehiculos1);
        btnVehiculos1.setLayout(btnVehiculos1Layout);
        btnVehiculos1Layout.setHorizontalGroup(
            btnVehiculos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVehiculos1Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(txtCliente3)
                .addGap(18, 18, 18)
                .addComponent(icoCarro1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnVehiculos1Layout.setVerticalGroup(
            btnVehiculos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icoCarro1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVehiculos1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCliente3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        MenuPlegable1.add(btnVehiculos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 230, 53));

        btnSalir1.setBackground(new java.awt.Color(64, 81, 115));
        btnSalir1.setRoundBottomLeft(25);
        btnSalir1.setRoundBottomRight(25);
        btnSalir1.setRoundTopLeft(25);
        btnSalir1.setRoundTopRight(25);
        btnSalir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalir1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalir1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalir1MouseExited(evt);
            }
        });

        txtBitacora3.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtBitacora3.setForeground(new java.awt.Color(255, 153, 153));
        txtBitacora3.setText("Cerrar secion");

        javax.swing.GroupLayout btnSalir1Layout = new javax.swing.GroupLayout(btnSalir1);
        btnSalir1.setLayout(btnSalir1Layout);
        btnSalir1Layout.setHorizontalGroup(
            btnSalir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSalir1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(txtBitacora3)
                .addGap(18, 18, 18)
                .addComponent(logOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnSalir1Layout.setVerticalGroup(
            btnSalir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSalir1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btnSalir1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBitacora3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        MenuPlegable1.add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, -1, -1));

        jPanel2.add(MenuPlegable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 0, 230, 820));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Envios Productos");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 390, 70));

        tbEnvios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbEnvios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEnviosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbEnvios);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 960, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCasaMouseClicked

    }//GEN-LAST:event_btnCasaMouseClicked

    private void btnCasaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCasaMouseEntered
        btnCasa.setBackground(new Color(45,40,37));
    }//GEN-LAST:event_btnCasaMouseEntered

    private void btnCasaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCasaMouseExited
        btnCasa.setBackground(new Color(64,81,115));
    }//GEN-LAST:event_btnCasaMouseExited

    private void txtBarrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBarrasMouseClicked
        if (MenuPlegable.getX()==-150) {
            desplace.desplazarDerecha(MenuPlegable, MenuPlegable.getX(), 0, 15, 10);
        } else if(MenuPlegable.getX() == 0) {
            desplace.desplazarIzquierda(MenuPlegable, MenuPlegable.getX(), -150, 15, 10);
        }
    }//GEN-LAST:event_txtBarrasMouseClicked

    private void btnProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoMouseClicked
        RProducto producto = new RProducto();
        producto.INIT();
        this.dispose();
    }//GEN-LAST:event_btnProductoMouseClicked

    private void btnProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoMouseEntered
        btnProducto.setBackground(new Color(45,40,37));
    }//GEN-LAST:event_btnProductoMouseEntered

    private void btnProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoMouseExited
        btnProducto.setBackground(new Color(64,81,115));
    }//GEN-LAST:event_btnProductoMouseExited

    private void btnClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMouseClicked
        RTiendas vista= new RTiendas();
        vista.INIT();
        this.dispose();
    }//GEN-LAST:event_btnClienteMouseClicked

    private void btnClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMouseEntered
        btnCliente.setBackground(new Color(45,40,37));
    }//GEN-LAST:event_btnClienteMouseEntered

    private void btnClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMouseExited
        btnCliente.setBackground(new Color(64,81,115));
    }//GEN-LAST:event_btnClienteMouseExited

    private void btnRutaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRutaMouseClicked
        REnvios rutas = new REnvios();
        rutas.INIT();
        this.dispose();
    }//GEN-LAST:event_btnRutaMouseClicked

    private void btnRutaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRutaMouseEntered
        btnRuta.setBackground(new Color(45,40,37));
    }//GEN-LAST:event_btnRutaMouseEntered

    private void btnRutaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRutaMouseExited
        btnRuta.setBackground(new Color(64,81,115));
    }//GEN-LAST:event_btnRutaMouseExited

    private void btnVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculosMouseClicked
        RVehiculos vista = new RVehiculos();
        vista.INIT();
        this.dispose();
    }//GEN-LAST:event_btnVehiculosMouseClicked

    private void btnVehiculosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVehiculosMouseEntered

    private void btnVehiculosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVehiculosMouseExited

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // [64,81,115]
        LoginPTC vista = new LoginPTC();
        vista.INIT();
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        btnSalir.setBackground(new Color(102,0,0));
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited

        btnSalir.setBackground(new Color(64,81,115));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnCasa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCasa1MouseClicked
        RMain vista = new RMain();
        vista.INIT();
        this.dispose();
    }//GEN-LAST:event_btnCasa1MouseClicked

    private void btnCasa1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCasa1MouseEntered
        btnCasa.setBackground(new Color(45,40,37));
    }//GEN-LAST:event_btnCasa1MouseEntered

    private void btnCasa1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCasa1MouseExited
        btnCasa.setBackground(new Color(64,81,115));
    }//GEN-LAST:event_btnCasa1MouseExited

    private void txtBarras1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBarras1MouseClicked
        if (MenuPlegable.getX()==-150) {
            desplace.desplazarDerecha(MenuPlegable, MenuPlegable.getX(), 0, 15, 10);
        } else if(MenuPlegable.getX() == 0) {
            desplace.desplazarIzquierda(MenuPlegable, MenuPlegable.getX(), -150, 15, 10);
        }
    }//GEN-LAST:event_txtBarras1MouseClicked

    private void btnProducto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProducto1MouseClicked
        RProducto producto = new RProducto();
        producto.INIT();
        this.dispose();
    }//GEN-LAST:event_btnProducto1MouseClicked

    private void btnProducto1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProducto1MouseEntered
        btnProducto.setBackground(new Color(45,40,37));
    }//GEN-LAST:event_btnProducto1MouseEntered

    private void btnProducto1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProducto1MouseExited
        btnProducto.setBackground(new Color(64,81,115));
    }//GEN-LAST:event_btnProducto1MouseExited

    private void btnCliente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCliente1MouseClicked
        RTiendas vista= new RTiendas();
        vista.INIT();
        this.dispose();
    }//GEN-LAST:event_btnCliente1MouseClicked

    private void btnCliente1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCliente1MouseEntered
        btnCliente.setBackground(new Color(45,40,37));
    }//GEN-LAST:event_btnCliente1MouseEntered

    private void btnCliente1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCliente1MouseExited
        btnCliente.setBackground(new Color(64,81,115));
    }//GEN-LAST:event_btnCliente1MouseExited

    private void btnRuta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRuta1MouseClicked

    }//GEN-LAST:event_btnRuta1MouseClicked

    private void btnRuta1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRuta1MouseEntered
        btnRuta.setBackground(new Color(45,40,37));
    }//GEN-LAST:event_btnRuta1MouseEntered

    private void btnRuta1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRuta1MouseExited
        btnRuta.setBackground(new Color(64,81,115));
    }//GEN-LAST:event_btnRuta1MouseExited

    private void btnVehiculos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculos1MouseClicked
        RVehiculos vista = new RVehiculos();
        vista.INIT();
        this.dispose();
    }//GEN-LAST:event_btnVehiculos1MouseClicked

    private void btnVehiculos1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculos1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVehiculos1MouseEntered

    private void btnVehiculos1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculos1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVehiculos1MouseExited

    private void btnSalir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalir1MouseClicked
        // [64,81,115]
        LoginPTC vista = new LoginPTC();
        vista.INIT();
        this.dispose();
    }//GEN-LAST:event_btnSalir1MouseClicked

    private void btnSalir1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalir1MouseEntered
        btnSalir.setBackground(new Color(102,0,0));
    }//GEN-LAST:event_btnSalir1MouseEntered

    private void btnSalir1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalir1MouseExited

        btnSalir.setBackground(new Color(64,81,115));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalir1MouseExited

    private void tbEnviosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEnviosMouseClicked

    }//GEN-LAST:event_tbEnviosMouseClicked

    /**
     * @param args the command line arguments
     */
    public void INIT(){
        RMain main= new RMain();
        BitacoraDistribuciones modelo = new BitacoraDistribuciones();
        modelo.RMostrarTablaM(main);
        main.setVisible(true);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Casaicon;
    private javax.swing.JLabel Casaicon1;
    private javax.swing.JLabel Clienteicon;
    private javax.swing.JLabel Clienteicon1;
    private javax.swing.JPanel MenuPlegable;
    private javax.swing.JPanel MenuPlegable1;
    private javax.swing.JLabel Productoicon;
    private javax.swing.JLabel Productoicon1;
    private javax.swing.JLabel Rutaicon;
    private javax.swing.JLabel Rutaicon1;
    private Vista.PanelCurvas btnCasa;
    private Vista.PanelCurvas btnCasa1;
    private Vista.PanelCurvas btnCliente;
    private Vista.PanelCurvas btnCliente1;
    private Vista.PanelCurvas btnProducto;
    private Vista.PanelCurvas btnProducto1;
    private Vista.PanelCurvas btnRuta;
    private Vista.PanelCurvas btnRuta1;
    private Vista.PanelCurvas btnSalir;
    private Vista.PanelCurvas btnSalir1;
    private Vista.PanelCurvas btnVehiculos;
    private Vista.PanelCurvas btnVehiculos1;
    private javax.swing.JLabel icoCarro;
    private javax.swing.JLabel icoCarro1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logOut;
    private javax.swing.JLabel logOut1;
    public javax.swing.JTable tbEnvios;
    private javax.swing.JLabel txtBarras;
    private javax.swing.JLabel txtBarras1;
    private javax.swing.JLabel txtBitacora2;
    private javax.swing.JLabel txtBitacora3;
    private javax.swing.JLabel txtCasa;
    private javax.swing.JLabel txtCasa1;
    private javax.swing.JLabel txtCliente;
    private javax.swing.JLabel txtCliente1;
    private javax.swing.JLabel txtCliente2;
    private javax.swing.JLabel txtCliente3;
    private javax.swing.JLabel txtLogo;
    private javax.swing.JLabel txtLogo1;
    private javax.swing.JLabel txtRuta;
    private javax.swing.JLabel txtRuta1;
    private javax.swing.JLabel txtproducto;
    private javax.swing.JLabel txtproducto1;
    // End of variables declaration//GEN-END:variables
}
